routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('tasks', 'TasksController');

app/Task.php
<?php

namespace App;

use App\Jobs\DownloadResource;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class Task extends Model
{
    /**
     * Pending status.
     * @var string
     */
    public const STATUS_PENDING = 'pending';

    /**
     * Downloading status.
     * @var string
     */
    public const STATUS_DOWNLOADING = 'downloading';

    /**
     * Complete status.
     * @var string
     */
    public const STATUS_COMPLETE = 'complete';

    /**
     * Error status.
     * @var string
     */
    public const STATUS_ERROR = 'error';

    /**
     * @var array
     */
    protected $fillable = ['url', 'resource', 'status', 'error_message'];

    /**
     * Get a download url for the downloaded resource.
     *
     * @return string
     */
    public function getDownloadUrlAttribute(): string
    {
        return Storage::url($this->resource);
    }

    /**
     * Generate a filename for the resource.
     *
     * @return string
     */
    public function generateResourceName(): string
    {
        $extension = pathinfo($this->url, PATHINFO_EXTENSION);
        if (empty($extension)) {
            $extension = 'html';
        }

        return sha1(time() . $this->url . rand(1, 10)) .'.'. $extension;
    }

    /**
     * Is task pending
     *
     * @return bool
     */
    public function isPending(): bool
    {
        return $this->status == self::STATUS_PENDING;
    }

    /**
     * Is task complete
     *
     * @return bool
     */
    public function isComplete(): bool
    {
        return $this->status == self::STATUS_COMPLETE;
    }

    /**
     * Is task in an error state
     *
     * @return bool
     */
    public function isError(): bool
    {
        return $this->status == self::STATUS_ERROR;
    }

    /**
     * Is task downloading
     *
     * @return bool
     */
    public function isDownloading(): bool
    {
        return $this->status == self::STATUS_DOWNLOADING;
    }

    /**
     * Store a new task in the database.
     *
     * @param Task $task
     * @param string $url
     * @return Task
     */
    public static function store(Task $task, string $url): Task
    {
        $task->url = $url;
        $task->status = Task::STATUS_PENDING;
        $task->save();

        dispatch(new DownloadResource($task));

        return $task;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Api/TasksController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\TaskRequest;
use App\Task;
use Illuminate\Database\Eloquent\Collection;

class TasksController extends Controller
{
    /**
     * List all tasks.
     *
     * @return Collection
     */
    public function index(): Collection
    {
        return Task::latest()->get();
    }

    /**
     * Store a new task in the database.
     *
     * @param Task $task
     * @param TaskRequest $request
     * @return Task
     */
    public function store(Task $task, TaskRequest $request): Task
    {
        return Task::store($task, $request->url);
    }

    /**
     * Delete a task.
     *
     * @param Task $task
     * @return bool|null
     */
    public function destroy(Task $task): string
    {
        $task->delete();

        return 'ok';
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaskRequest;
use App\Repositories\TaskRepository;
use App\Task;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class TasksController extends Controller
{
    /**
     * Show all tasks.
     *
     * @return View
     */
    public function index(): View
    {
        $tasks = Task::latest()->get();

        return view('tasks.index', compact('tasks'));
    }

    /**
     * Create a new task.
     *
     * @param Task $task
     * @param TaskRequest $request
     * @return RedirectResponse
     */
    public function store(Task $task, TaskRequest $request): RedirectResponse
    {
        Task::store($task, $request->url);

        session()->flash('message', 'Task has been created');
        return back();
    }

    /**
     * Delete a task.
     *
     * @param Task $task
     * @return RedirectResponse
     */
    public function destroy(Task $task)
    {
        $task->delete();

        session()->flash('message', 'Task has been removed.');

        return back();
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>
    </head>
    <body>
        @yield('content')
    </body>
</html>

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')
    @if (session()->has('message'))
        <div style="padding-bottom: 20px;">
            {{ session()->get('message') }}
        </div>
    @endif

    <form action="{{ route('tasks.store') }}" method="post">
        {{ csrf_field() }}

        @if ($errors->count())
            {{ dump($errors->all()) }}
        @endif

        <input type="text" name="url" placeholder="Resource URL" required>
        <input type="submit" value="Download">
    </form>

    <table border="1">
        <thead>
        <tr>
            <th>#</th>
            <th>Date/Time</th>
            <th>Resource</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse ($tasks as $task)
            <tr>
                <td>{{ $task->id }}</td>
                <td>{{ $task->created_at->format('Y-m-d H:i:s') }}</td>
                <td>{{ $task->url }}</td>
                <td>{{ $task->status }}</td>
                <td>
                    @if ($task->isPending())
                    <form id="delete-{{ $task->id }}" action="{{ route('tasks.destroy', $task) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>

                    <a href="#" onclick="document.getElementById('delete-{{ $task->id }}').submit()" style="color: red">
                        Remove
                    </a>
                    @endif

                    @if ($task->isComplete())
                        <a href="{{ $task->download_url }}">Download</a>
                    @endif

                    @if ($task->isError())
                        {{ $task->error_message }}
                    @endif
                </td>
            </tr>
        @empty
            <tr>
                <td align="center" colspan="5">
                    <h2>Tasks not found.</h2>
                </td>
            </tr>
        @endforelse
        </tbody>
    </table>
@endsection